customProperties:"formComponent:false,\
layout:{\
responsive:true\
}",
dataSource:"db:/example_data/orders",
encapsulation:60,
name:"Settings",
navigatorID:"-1",
showInMenu:true,
typeid:3,
uuid:"2DB7F39E-BD21-4731-A3D6-680E0BABA2FE"